<?php

use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    private static $content = "<h2>Bacon ipsum</h2>"
        ."<p>Dolor amet ball tip ham hock tail, jerky pork loin beef ribs landjaeger fatback tri-tip ribeye andouille t-bone. Doner biltong andouille kevin turkey picanha venison t-bone turducken pork pancetta. Pig landjaeger t-bone burgdoggen pastrami sausage. Meatloaf short ribs shoulder t-bone burgdoggen short loin jerky. Landjaeger cow beef, strip steak pig jowl turkey frankfurter pork loin bacon prosciutto porchetta.</p>"
        ."<h2>Shankle pancetta</h2>"
        ."<p>Landjaeger turkey brisket sirloin strip steak sausage pastrami chicken kielbasa ham ball tip drumstick. Hamburger pork chop prosciutto shank shankle, fatback doner. Ham hock strip steak meatball venison, sausage tongue jerky bacon pastrami. Ground round picanha shoulder landjaeger.</p>"
        ."<h2>Cupim tenderloin beef</h2>"
        ."<p>Shoulder. Drumstick tri-tip beef ribs, jerky alcatra turducken short ribs biltong chicken. Kielbasa t-bone alcatra beef ribs biltong chicken salami landjaeger pancetta pork belly. Short ribs tongue shankle alcatra hamburger cow. Turkey short loin shankle hamburger doner biltong swine pig ham strip steak andouille.</p>"
        ."<h2>Shankle tail prosciutto fatback</h2>"
        ."<p>Turducken pork short ribs short loin, rump leberkas bresaola kielbasa capicola flank t-bone. Capicola jerky bacon pig meatloaf, ham pork belly short loin pork chop. Picanha venison andouille meatball shankle. Short loin ham venison, ball tip t-bone turkey pork chop filet mignon bacon doner. Jowl beef ribs jerky short ribs turducken filet mignon pig venison beef corned beef t-bone.</p>"
        ."<h2>Short ribs</h2>"
        ."<p>swine tongue pork chop, boudin pork belly porchetta picanha buffalo doner ham flank meatloaf chuck. Ham hock doner flank, turkey tail chuck pastrami short loin shoulder pork chop bacon frankfurter. Cupim sausage pork leberkas alcatra corned beef turducken ball tip rump shankle chicken spare ribs tenderloin jowl prosciutto. Filet mignon cow meatloaf drumstick pork chop pancetta. Jerky chuck biltong, sausage alcatra t-bone pastrami capicola bacon beef ribeye tongue.</p>";

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            ['id'=>1,'name'=>'QuietComfort 35 wireless headphones II','slug'=>'quietcomfort-35-wireless-headphones-ii','org_price'=>349.95,'dct_price'=>299.95,'qty'=>100],
            ['id'=>2,'name'=>'Custom QuietComfort 35 wireless headphones II','slug'=>'custom-quietcomfort-35-wireless-headphones-ii','org_price'=>399.45,'dct_price'=>NULL,'qty'=>100],
            ['id'=>3,'name'=>'QC25 noise cancelling headphones Apple devices','slug'=>'qc25-noise-cancelling-headphones-apple-devices','org_price'=>179.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>4,'name'=>'QuietControl 30 wireless headphones','slug'=>'quietcontrol-30-wireless-headphones','org_price'=>299.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>5,'name'=>'QC20 noise cancelling headphones Apple devices','slug'=>'qc20-noise-cancelling-headphones-apple-devices','org_price'=>249.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>6,'name'=>'QC20 noise cancelling headphones Samsung/Android devices','slug'=>'qc20-noise-cancelling-headphones-samsung-android-devices','org_price'=>249.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>7,'name'=>'SoundSport Free wireless headphones','slug'=>'soundsport-free-wireless-headphones','org_price'=>199.95,'dct_price'=>169.95,'qty'=>100],
            ['id'=>8,'name'=>'SoundSport wireless headphones','slug'=>'soundsport-wireless-headphones','org_price'=>149.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>9,'name'=>'SoundLink around-ear wireless headphones II','slug'=>'soundlink-around-ear-wireless-headphones-ii','org_price'=>229.95,'dct_price'=>199.95,'qty'=>100],
            ['id'=>10,'name'=>'SoundWear Companion speaker','slug'=>'soundwear-companion-speaker','org_price'=>299.95,'dct_price'=>249.95,'qty'=>100],
            ['id'=>11,'name'=>'Bose on-ear wireless headphones','slug'=>'bose-on-ear-wireless-headphones','org_price'=>179.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>12,'name'=>'SoundSport Pulse wireless headphones','slug'=>'soundsport-pulse-wireless-headphones','org_price'=>199.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>13,'name'=>'BOSEbuild Headphones','slug'=>'bosebuild-headphones','org_price'=>149.95,'dct_price'=>119.95,'qty'=>100],
            ['id'=>14,'name'=>'SoundSport in-ear headphones Apple devices','slug'=>'soundsport-in-ear-headphones-apple-devices','org_price'=>99.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>15,'name'=>'SoundSport in-ear headphones Samsung/Android devices','slug'=>'soundsport-in-ear-headphones-samsung-android-devices','org_price'=>99.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>16,'name'=>'Proflight aviation headset','slug'=>'proflight-aviation-headset','org_price'=>999.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>17,'name'=>'A20 aviation headset','slug'=>'a20-aviation-headset','org_price'=>999.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>18,'name'=>'Bose noise-masking sleepbuds','slug'=>'bose-noise-masking-sleepbuds','org_price'=>249.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>19,'name'=>'Bose Hearphones','slug'=>'bose-hearphones','org_price'=>499.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>20,'name'=>'ProFlight accessory kit','slug'=>'proflight-accessory-kit','org_price'=>31.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>21,'name'=>'ProFlight carry case','slug'=>'proflight-carry-case','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>22,'name'=>'ProFlight Headset cable, 5-pin XLR','slug'=>'proflight-headset-cable-5-pin-xlr','org_price'=>295.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>23,'name'=>'ProFlight control module lanyard','slug'=>'proflight-control-module-lanyard','org_price'=>4.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>24,'name'=>'ProFlight termination cap','slug'=>'proflight-termination-cap','org_price'=>4.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>25,'name'=>'ProFlight microphone windscreen','slug'=>'proflight-microphone-windscreen','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>26,'name'=>'ProFlight headband pad','slug'=>'proflight-headband-pad','org_price'=>12.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>27,'name'=>'ProFlight Headset cable, 6-pin Lemo','slug'=>'proflight-headset-cable-6-pin-lemo','org_price'=>295.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>28,'name'=>'ProFlight side cushions','slug'=>'proflight-side-cushions','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>29,'name'=>'ProFlight Headset cable, dual plugs','slug'=>'proflight-headset-cable-dual-plugs','org_price'=>295.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>30,'name'=>'StayHear+ Sleep tips (2 pairs)','slug'=>'stayhearplus-sleep-tips-2-pairs','org_price'=>7.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>31,'name'=>'QuietComfort 15 and 2 headphones ear cushion kit','slug'=>'quietcomfort-15-and-2-headphones-ear-cushion-kit','org_price'=>35,'dct_price'=>NULL,'qty'=>100],
            ['id'=>32,'name'=>'SoundLink on-ear cushion kit','slug'=>'soundlink-on-ear-cushion-kit','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>33,'name'=>'StayHear+ Sport tips (2 pairs)','slug'=>'stayhearplus-sport-tips-2-pairs','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>34,'name'=>'QC airline adapter','slug'=>'qc-airline-adapter','org_price'=>7.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>35,'name'=>'QC35 ear cushion kit','slug'=>'qc35-ear-cushion-kit','org_price'=>34.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>36,'name'=>'SoundLink wireless headphones II audio cable','slug'=>'soundlink-wireless-headphones-ii-audio-cable','org_price'=>6.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>37,'name'=>'SoundSport charging case','slug'=>'soundsport-charging-case','org_price'=>49.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>38,'name'=>'StayHear tips (2 pr)','slug'=>'stayhear-tips-2-pr','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>39,'name'=>'QC25 ear cushion kit','slug'=>'qc25-ear-cushion-kit','org_price'=>34.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>40,'name'=>'QC25 inline mic/remote Samsung and Android devices','slug'=>'qc25-inline-mic-remote-samsung-and-android-devices','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>41,'name'=>'USB cable','slug'=>'usb-cable','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>42,'name'=>'SoundLink wireless headphones II ear cushion kit','slug'=>'soundlink-wireless-headphones-ii-ear-cushion-kit','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>43,'name'=>'SoundSport wireless headphones carry case','slug'=>'soundsport-wireless-headphones-carry-case','org_price'=>12.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>44,'name'=>'SoundSport wireless headphones clothing clip','slug'=>'soundsport-wireless-headphones-clothing-clip','org_price'=>3.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>45,'name'=>'SoundSport Free portable charging case','slug'=>'soundsport-free-portable-charging-case','org_price'=>49.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>46,'name'=>'QC35 carry case','slug'=>'qc35-carry-case','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>47,'name'=>'QC20 headphones clothing clip','slug'=>'qc20-headphones-clothing-clip','org_price'=>3.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>48,'name'=>'Wall charger plus international adapters','slug'=>'wall-charger-plus-international-adapters','org_price'=>19.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>49,'name'=>'SoundLink on-ear audio cable','slug'=>'soundlink-on-ear-audio-cable','org_price'=>6.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>50,'name'=>'QC25 inline mic/remote Apple devices','slug'=>'qc25-inline-mic-remote-apple-devices','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>51,'name'=>'QuietComfort 15 audio cable','slug'=>'quietcomfort-15-audio-cable','org_price'=>15,'dct_price'=>NULL,'qty'=>100],
            ['id'=>52,'name'=>'A20 ear cushions','slug'=>'a20-ear-cushions','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>53,'name'=>'AE2 headphones replacement audio cable','slug'=>'ae2-headphones-replacement-audio-cable','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>54,'name'=>'StayHear+ tips (2 pr)','slug'=>'stayhearplus-tips-2-pr','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>55,'name'=>'QuietControl Stayhear+ tips (2 pairs)','slug'=>'quietcontrol-stayhearplus-tips-2-pairs','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>56,'name'=>'QuietComfort 3 ear cushion kit','slug'=>'quietcomfort-3-ear-cushion-kit','org_price'=>35,'dct_price'=>NULL,'qty'=>100],
            ['id'=>57,'name'=>'QC20 carry case','slug'=>'qc20-carry-case','org_price'=>14.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>58,'name'=>'SoundLink wireless headphones II carry case','slug'=>'soundlink-wireless-headphones-ii-carry-case','org_price'=>19.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>59,'name'=>'StayHear Ultra tips (2 pr)','slug'=>'stayhear-ultra-tips-2-pr','org_price'=>9.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>60,'name'=>'SoundSport Pulse Stayhear+ tips (2 pairs) ','slug'=>'soundsport-pulse-stayhearplus-tips-2-pairs-','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>61,'name'=>'QuietComfort 3 audio cable','slug'=>'quietcomfort-3-audio-cable','org_price'=>15,'dct_price'=>NULL,'qty'=>100],
            ['id'=>62,'name'=>'6-pin to dual G/A plug adapter','slug'=>'6-pin-to-dual-g-a-plug-adapter','org_price'=>59.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>63,'name'=>'SoundSport carry case','slug'=>'soundsport-carry-case','org_price'=>12.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>64,'name'=>'A20 Headset high impedance microphone windscreen','slug'=>'a20-headset-high-impedance-microphone-windscreen','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>65,'name'=>'SoundLink on-ear carry case','slug'=>'soundlink-on-ear-carry-case','org_price'=>19.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>66,'name'=>'SoundLink Color Bluetooth speaker II','slug'=>'soundlink-color-bluetooth-speaker-ii','org_price'=>129.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>67,'name'=>'SoundLink Revolve+ Bluetooth speaker','slug'=>'soundlink-revolveplus-bluetooth-speaker','org_price'=>299.95,'dct_price'=>269.95,'qty'=>100],
            ['id'=>68,'name'=>'SoundLink Micro Bluetooth speaker','slug'=>'soundlink-micro-bluetooth-speaker','org_price'=>99.95,'dct_price'=>79.95,'qty'=>100],
            ['id'=>69,'name'=>'SoundLink Mini Bluetooth speaker II','slug'=>'soundlink-mini-bluetooth-speaker-ii','org_price'=>199.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>70,'name'=>'BOSEbuild Speaker Cube','slug'=>'bosebuild-speaker-cube','org_price'=>99.95,'dct_price'=>69.95,'qty'=>100],
            ['id'=>71,'name'=>'SoundLink Revolve Bluetooth speaker','slug'=>'soundlink-revolve-bluetooth-speaker','org_price'=>199.95,'dct_price'=>179.95,'qty'=>100],
            ['id'=>72,'name'=>'S1 Pro system','slug'=>'s1-pro-system','org_price'=>599.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>73,'name'=>'Bose Home Speaker 500','slug'=>'bose-home-speaker-500','org_price'=>399.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>74,'name'=>'Bose Soundbar 700','slug'=>'bose-soundbar-700','org_price'=>799.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>75,'name'=>'Bose Soundbar 500','slug'=>'bose-soundbar-500','org_price'=>549.95,'dct_price'=>499.95,'qty'=>100],
            ['id'=>76,'name'=>'Bose Surround Speakers','slug'=>'bose-surround-speakers','org_price'=>299.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>77,'name'=>'Bose Bass Module 700','slug'=>'bose-bass-module-700','org_price'=>699.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>78,'name'=>'Bose Bass Module 500','slug'=>'bose-bass-module-500','org_price'=>399.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>79,'name'=>'SoundTouch 10 wireless speaker','slug'=>'soundtouch-10-wireless-speaker','org_price'=>199.95,'dct_price'=>169.95,'qty'=>100],
            ['id'=>80,'name'=>'SoundTouch 20 wireless speaker','slug'=>'soundtouch-20-wireless-speaker','org_price'=>349.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>81,'name'=>'SoundTouch 30 wireless speaker','slug'=>'soundtouch-30-wireless-speaker','org_price'=>499.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>82,'name'=>'SoundTouch Wireless Link adapter','slug'=>'soundtouch-wireless-link-adapter','org_price'=>149.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>83,'name'=>'SoundTouch SA-5 amplifier','slug'=>'soundtouch-sa-5-amplifier','org_price'=>499.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>84,'name'=>'SoundTouch outdoor wireless system with 251 speakers','slug'=>'soundtouch-outdoor-wireless-system-with-251-speakers','org_price'=>898.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>85,'name'=>'Bose Solo 5 TV sound system','slug'=>'bose-solo-5-tv-sound-system','org_price'=>249.95,'dct_price'=>199.95,'qty'=>100],
            ['id'=>86,'name'=>'Acoustimass 10 home theater speaker system','slug'=>'acoustimass-10-home-theater-speaker-system','org_price'=>999.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>87,'name'=>'Lifestyle 650 home entertainment system','slug'=>'lifestyle-650-home-entertainment-system','org_price'=>3999.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>88,'name'=>'Lifestyle 600 home entertainment system','slug'=>'lifestyle-600-home-entertainment-system','org_price'=>2999.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>89,'name'=>'SoundTouch 300 soundbar','slug'=>'soundtouch-300-soundbar','org_price'=>699.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>90,'name'=>'Wave system IV','slug'=>'wave-system-iv','org_price'=>499.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>91,'name'=>'Wave SoundTouch music system IV','slug'=>'wave-soundtouch-music-system-iv','org_price'=>599.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>92,'name'=>'Companion 2 computer speakers','slug'=>'companion-2-computer-speakers','org_price'=>99.95,'dct_price'=>89.95,'qty'=>100],
            ['id'=>93,'name'=>'Acoustimass 5 stereo speaker system','slug'=>'acoustimass-5-stereo-speaker-system','org_price'=>399.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>94,'name'=>'301 bookshelf speakers','slug'=>'301-bookshelf-speakers','org_price'=>328.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>96,'name'=>'Companion 20 computer speakers','slug'=>'companion-20-computer-speakers','org_price'=>249.95,'dct_price'=>224.95,'qty'=>100],
            ['id'=>97,'name'=>'151 outdoor speakers','slug'=>'151-outdoor-speakers','org_price'=>278.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>98,'name'=>'161 bookshelf speakers','slug'=>'161-bookshelf-speakers','org_price'=>158.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>99,'name'=>'791 in-ceiling speakers II','slug'=>'791-in-ceiling-speakers-ii','org_price'=>599.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>100,'name'=>'Free Space 51 outdoor speakers','slug'=>'free-space-51-outdoor-speakers','org_price'=>449.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>101,'name'=>'251 outdoor speakers','slug'=>'251-outdoor-speakers','org_price'=>398.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>103,'name'=>'201 bookshelf speakers','slug'=>'201-bookshelf-speakers','org_price'=>218.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>104,'name'=>'891 in-wall speakers','slug'=>'891-in-wall-speakers','org_price'=>599.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>105,'name'=>'591 in-ceiling speakers','slug'=>'591-in-ceiling-speakers','org_price'=>449.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>106,'name'=>'691 in-wall speakers','slug'=>'691-in-wall-speakers','org_price'=>449.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>107,'name'=>'L1 Compact system','slug'=>'l1-compact-system','org_price'=>849.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>108,'name'=>'F1 Model 812 loudspeaker with F1 Subwoofer','slug'=>'f1-model-812-loudspeaker-with-f1-subwoofer','org_price'=>2399.9,'dct_price'=>2039.91,'qty'=>100],
            ['id'=>109,'name'=>'F1 Model 812 Flexible Array loudspeaker','slug'=>'f1-model-812-flexible-array-loudspeaker','org_price'=>1199.95,'dct_price'=>1019.96,'qty'=>100],
            ['id'=>110,'name'=>'L1 II system/B2 bass','slug'=>'l1-ii-system-b2-bass','org_price'=>2699.95,'dct_price'=>2294.96,'qty'=>100],
            ['id'=>111,'name'=>'L1 Compact Wireless package','slug'=>'l1-compact-wireless-package','org_price'=>1099.95,'dct_price'=>934.96,'qty'=>100],
            ['id'=>112,'name'=>'T4S ToneMatch mixer','slug'=>'t4s-tonematch-mixer','org_price'=>599.95,'dct_price'=>509.95,'qty'=>100],
            ['id'=>113,'name'=>'T8S ToneMatch mixer','slug'=>'t8s-tonematch-mixer','org_price'=>899.95,'dct_price'=>764.95,'qty'=>100],
            ['id'=>114,'name'=>'F1 Subwoofer','slug'=>'f1-subwoofer','org_price'=>1199.95,'dct_price'=>1019.96,'qty'=>100],
            ['id'=>115,'name'=>'L1 1S system/B2 bass','slug'=>'l1-1s-system-b2-bass','org_price'=>1999.95,'dct_price'=>1699.96,'qty'=>100],
            ['id'=>116,'name'=>'L1 1S system/B1 bass','slug'=>'l1-1s-system-b1-bass','org_price'=>1799.95,'dct_price'=>1529.96,'qty'=>100],
            ['id'=>117,'name'=>'L1 II system/B1 bass','slug'=>'l1-ii-system-b1-bass','org_price'=>2499.95,'dct_price'=>2124.96,'qty'=>100],
            ['id'=>118,'name'=>'Two F1 Model 812 loudspeakers with F1 Subwoofer','slug'=>'two-f1-model-812-loudspeakers-with-f1-subwoofer','org_price'=>3599.95,'dct_price'=>3057.87,'qty'=>100],
            ['id'=>119,'name'=>'SoundLink Revolve charging cradle','slug'=>'soundlink-revolve-charging-cradle','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>120,'name'=>'Bose Soundbar Wall Bracket','slug'=>'bose-soundbar-wall-bracket','org_price'=>39.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>121,'name'=>'Bose Soundbar Universal Remote','slug'=>'bose-soundbar-universal-remote','org_price'=>49.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>122,'name'=>'SoundXtra TV stand for SoundTouch 300','slug'=>'soundxtra-tv-stand-for-soundtouch-300','org_price'=>129.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>123,'name'=>'S1 Pro Slip Cover','slug'=>'s1-pro-slip-cover','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>124,'name'=>'S1 Pro Backpack','slug'=>'s1-pro-backpack','org_price'=>149.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>125,'name'=>'SoundXtra floor stand for SoundTouch 20','slug'=>'soundxtra-floor-stand-for-soundtouch-20','org_price'=>129.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>126,'name'=>'Wave FM antenna','slug'=>'wave-fm-antenna','org_price'=>9.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>127,'name'=>'RC-PWS III universal remote','slug'=>'rc-pws-iii-universal-remote','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>128,'name'=>'UB-20 II wall/ceiling bracket','slug'=>'ub-20-ii-wall-ceiling-bracket','org_price'=>34.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>129,'name'=>'UFS-20 II floorstands','slug'=>'ufs-20-ii-floorstands','org_price'=>119.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>130,'name'=>'SoundWear Companion cover','slug'=>'soundwear-companion-cover','org_price'=>29.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>131,'name'=>'Speaker wire adapter kot','slug'=>'speaker-wire-adapter-kot','org_price'=>39.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>132,'name'=>'B1 bass module','slug'=>'b1-bass-module','org_price'=>299.95,'dct_price'=>254.96,'qty'=>100],
            ['id'=>133,'name'=>'SlideConnect wall bracket','slug'=>'slideconnect-wall-bracket','org_price'=>35.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>134,'name'=>'WB-300 wall bracket','slug'=>'wb-300-wall-bracket','org_price'=>39.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>135,'name'=>'WB-120 wall-mount kit','slug'=>'wb-120-wall-mount-kit','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>136,'name'=>'L1 Compact microphone accessory pack','slug'=>'l1-compact-microphone-accessory-pack','org_price'=>149.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>137,'name'=>'SoundLink Mini travel bag','slug'=>'soundlink-mini-travel-bag','org_price'=>44.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>138,'name'=>'UTS-20 II table stand','slug'=>'uts-20-ii-table-stand','org_price'=>34.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>139,'name'=>'CineMate speaker wire adapter kit','slug'=>'cinemate-speaker-wire-adapter-kit','org_price'=>39.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>140,'name'=>'B1/B2 4-pin cable','slug'=>'b1-b2-4-pin-cable','org_price'=>29.99,'dct_price'=>NULL,'qty'=>100],
            ['id'=>141,'name'=>'SoundXtra TV mount for SoundTouch 300','slug'=>'soundxtra-tv-mount-for-soundtouch-300','org_price'=>119.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>142,'name'=>'SoundLink speaker III cover','slug'=>'soundlink-speaker-iii-cover','org_price'=>34.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>143,'name'=>'PackLite A1 power amplifier','slug'=>'packlite-a1-power-amplifier','org_price'=>399.95,'dct_price'=>339.95,'qty'=>100],
            ['id'=>144,'name'=>'WB-3 bookshelf speaker wall brackets','slug'=>'wb-3-bookshelf-speaker-wall-brackets','org_price'=>19.98,'dct_price'=>NULL,'qty'=>100],
            ['id'=>145,'name'=>'B2 bass module','slug'=>'b2-bass-module','org_price'=>424.96,'dct_price'=>NULL,'qty'=>100],
            ['id'=>146,'name'=>'ToneMatch mixer power supply','slug'=>'tonematch-mixer-power-supply','org_price'=>50.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>147,'name'=>'SoundLink Revolve and Soundlink Revolve+ wall adapter','slug'=>'soundlink-revolve-and-soundlink-revolveplus-wall-adapter','org_price'=>24.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>148,'name'=>'FS-01 bookshelf speaker floorstands','slug'=>'fs-01-bookshelf-speaker-floorstands','org_price'=>89.98,'dct_price'=>NULL,'qty'=>100],
            ['id'=>149,'name'=>'Home theater speaker extension cable','slug'=>'home-theater-speaker-extension-cable','org_price'=>14.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>150,'name'=>'Lifestyle 600/650 home entertainment system remote control','slug'=>'lifestyle-600-650-home-entertainment-system-remote-control','org_price'=>99.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>151,'name'=>'SoundTouch II remote','slug'=>'soundtouch-ii-remote','org_price'=>14.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>152,'name'=>'OmniJewel center channel wire adapter','slug'=>'omnijewel-center-channel-wire-adapter','org_price'=>5.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>153,'name'=>'SoundXtra wall mount for SoundTouch 10','slug'=>'soundxtra-wall-mount-for-soundtouch-10','org_price'=>44.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>154,'name'=>'791 in-ceiling speakers II rough-in kit','slug'=>'791-in-ceiling-speakers-ii-rough-in-kit','org_price'=>64.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>155,'name'=>'WB-135 wall mount kit','slug'=>'wb-135-wall-mount-kit','org_price'=>49.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>156,'name'=>'CineMate home theater system-Interface Module','slug'=>'cinemate-home-theater-system-interface-module','org_price'=>79.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>157,'name'=>'F1 Model 812 travel bag','slug'=>'f1-model-812-travel-bag','org_price'=>139,'dct_price'=>118.15,'qty'=>100],
            ['id'=>158,'name'=>'891 in-wall speakers rough-in kit','slug'=>'891-in-wall-speakers-rough-in-kit','org_price'=>64.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>159,'name'=>'SoundXtra floor stand for SoundTouch 10','slug'=>'soundxtra-floor-stand-for-soundtouch-10','org_price'=>99.95,'dct_price'=>NULL,'qty'=>100],
            ['id'=>160,'name'=>'SoundXtra floor stand for SoundTouch 30','slug'=>'soundxtra-floor-stand-for-soundtouch-30','org_price'=>169.95,'dct_price'=>NULL,'qty'=>100],
            
        ];

        foreach($data as $k => $record) {
            $record['description'] = self::$content;
            DB::table('products')->insert($record);
        }
    }
}
